#!/bin/bash

ssh_host=peter@gigamonkeys.com
quicklisp_root=/var/www/www.gigamonkeys.com/quicklisp

rsync --archive --progress ./archives/ $ssh_host:$quicklisp_root/archives/
rsync --archive --progress ./monkeylib/ $ssh_host:$quicklisp_root/monkeylib/